log_dir = "{{pkg.svc_var_path}}"

[ui]
root = "{{pkg.svc_static_path}}"

[http]
{{toToml cfg.http}}

{{#if cfg.github.enabled ~}}
[github]
app_private_key = "{{pkg.svc_files_path}}/builder-github-app.pem"
{{toToml cfg.github}}
{{/if ~}}

{{#if cfg.bitbucket.enabled ~}}
[bitbucket]
{{toToml cfg.bitbucket}}
{{/if ~}}

[segment]
{{toToml cfg.segment}}

{{~#eachAlive bind.router.members as |member|}}
[[routers]]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/eachAlive}}

[depot]
path = "{{pkg.svc_data_path}}"
log_dir = "{{pkg.svc_var_path}}"
key_dir = "{{pkg.svc_files_path}}"
{{toToml cfg.depot}}

{{#if cfg.s3 ~}}
[s3]
{{toToml cfg.s3}}
{{/if ~}}
