log_level = "info"

[http]
listen = "0.0.0.0"
port   = 9636

[github]
enabled        = false
api_url        = "https://api.github.com"
token_url      = "https://github.com/login/oauth/access_token"
redirect_url   = ""
client_id      = ""
client_secret  = ""
app_id         = 5565
webhook_secret = ""

[bitbucket]
enabled        = false
api_url        = "https://api.bitbucket.org"
token_url      = "https://bitbucket.org/site/oauth2/access_token"
client_id      = ""
client_secret  = ""

[depot]
builds_enabled          = true
non_core_builds_enabled = true
events_enabled          = false

[s3]
aws_key_id              = "XXXXXXXXXXXXXXXXXXXX"
aws_secret_key          = "XXXXXxxXxXxXXXXxXXxXxXxxxxxXXxXXXxXxxXXx"
aws_region              = "us-east-2"
s3bucket                = "habitat-builder-artifact-store"

[segment]
url       = "https://api.segment.io"
write_key = ""
