[package]
name = "habitat_depot"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
description = "Habitat-Builder package depot"
workspace = "../../"

[dependencies]
clippy = { version = "*", optional = true }
base64 = "*"
bodyparser = "*"
env_logger = "*"
futures = "0.1.16"
habitat-builder-protocol = { path = "../builder-protocol" }
builder-http-gateway = { path = "../builder-http-gateway" }
hyper = "0.10"
iron = "*"
iron-test = "*"
libc = "*"
libarchive = "*"
log = "*"
mount = "*"
persistent = "*"
protobuf = "*"
r2d2 = "*"
regex = "*"
router = "*"
rusoto_core = "*"
rusoto_s3 = "*"
rust-crypto = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tempfile = "*"
time = "*"
toml = { version = "*", default-features = false }
unicase = "*"
url = "*"
walkdir = "*"
uuid = { version = "*", features = ["v4"] }

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.builder_core]
path = "../builder-core"

[dependencies.github-api-client]
path = "../github-api-client"

[dependencies.bitbucket-api-client]
path = "../bitbucket-api-client"

[dependencies.segment-api-client]
path = "../segment-api-client"

[dependencies.habitat_core]
git = "https://github.com/habitat-sh/core.git"

[dependencies.habitat_net]
path = "../net"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
branch = "release/v0.8"
